mtdbt2f-4d --steps 70 --exit 700 --weight 5 200 --slant -.2 .2 --super .5 .8 --pen 0 .333 3 0 720
mtdbt2f-4d --steps 20 --exit 100 --weight 5 350 --slant 0 0 --super .75 .75 --pen 0 1 1 0 0 --counter 700
mtdbt2f-4d --steps 20 --exit 100 --weight 50 50 --slant -2 2 --super .75 .75 --pen 0 1 1 0 0 --counter 800
mtdbt2f-4d --steps 20 --exit 100 --weight 50 50 --slant 0 0 --super .1 .9 --pen 0 1 1 0 0 --counter 900
mtdbt2f-4d --steps 100 --exit 100 --weight 50 50 --slant 0 0 --super .75 .75 --pen 0 .333 .333 0 720 --counter 1000
mtdbt2f-4d --steps 100 --exit 122 --weight 10 250 --slant -.5 .5 --super .4 .9 --pen 0 .1 20 0 720
