#!/bin/bash

# this is used to check on next candidate for release
# read first from text file of last known release
# then try if the next file exists --
# if so, then cp etc and also update the text file
# number of last release is in mtdbt2f4d.txt
# running as .sh in cron requires aboslute paths
# src.zip (pass: mtdbt2f4d)
# * updated to work with global variables for paths *
# assumes paths relative to this file unless explicitly stated

COUNTER=0
EXIT=521			# the total number of fonts to try
SLEEP=5				# this if for dev only
RELEASED=$(cat mtdbt2f4d.txt)	# more robust

# configuration
										# quotes to avoid file disasters (*,.,etc.)
LOCAL="."									# use . for relative, or specify
REMOTE="~/public_html/drupal/sites/kadist.org/files/mtdbt2f4d"			# public www server distrubution
LIVE="~/www/drupal/sites/all/themes/gui/kadist/css/metafont/metafont-webfont"	# live www deployment

# unpack archive
# does not work in cron
unzip -q -P mtdbt2f4d -d "$LOCAL" src.zip

# main

let CANDIDATE=RELEASED+1

if [ $CANDIDATE -gt $EXIT ]; then
	let CANDIDATE=0
fi

while [ $COUNTER -lt $EXIT ]; do

	if [ -f "$LOCAL"/.ttf/mtdbt2f4d-$CANDIDATE.ttf ]; then

		echo $CANDIDATE > "$LOCAL"/mtdbt2f4d.txt
		echo "** mtdbt2f4d-$CANDIDATE.ttf ** released."

		# backup
		cp "$REMOTE"/pdf/mtdbt2f4d.pdf "$REMOTE"/pdf/mtdbt2f4d-$RELEASED.pdf
		cp "$REMOTE"/png/mtdbt2f4d.png "$REMOTE"/png/mtdbt2f4d-$RELEASED.png
		cp "$REMOTE"/ttf/mtdbt2f4d.ttf "$REMOTE"/ttf/mtdbt2f4d-$RELEASED.ttf
		cp "$REMOTE"/eot/mtdbt2f4d.eot "$REMOTE"/eot/mtdbt2f4d-$RELEASED.eot
		cp "$REMOTE"/woff/mtdbt2f4d.woff "$REMOTE"/woff/mtdbt2f4d-$RELEASED.woff

		# install
		cp "$LOCAL"/.pdf/mtdbt2f4d-$CANDIDATE.pdf "$REMOTE"/pdf/mtdbt2f4d.pdf
		cp "$LOCAL"/.png/mtdbt2f4d-$CANDIDATE.png "$REMOTE"/png/mtdbt2f4d.png
		cp "$LOCAL"/.ttf/mtdbt2f4d-$CANDIDATE.ttf "$REMOTE"/ttf/mtdbt2f4d.ttf
		cp "$LOCAL"/.eot/mtdbt2f4d-$CANDIDATE.eot "$REMOTE"/eot/mtdbt2f4d.eot
		cp "$LOCAL"/.woff/mtdbt2f4d-$CANDIDATE.woff "$REMOTE"/woff/mtdbt2f4d.woff
		cp "$LOCAL"/.ttf/mtdbt2f4d-$CANDIDATE.ttf "$LIVE"/mtdbt2f4d.ttf
		cp "$LOCAL"/.eot/mtdbt2f4d-$CANDIDATE.eot "$LIVE"/mtdbt2f4d.eot
		cp "$LOCAL"/.woff/mtdbt2f4d-$CANDIDATE.woff "$LIVE"/mtdbt2f4d.woff

		# public url 	** out of date **
		# http://temp.kadist.org/sites/kadist.org/files/mtdbt2f4d/pdf/mtdbt2f4d.pdf
		# http://temp.kadist.org/sites/kadist.org/files/mtdbt2f4d/png/mtdbt2f4d.png
		# http://temp.kadist.org/sites/kadist.org/files/mtdbt2f4d/ttf/mtdbt2f4d.ttf
		# http://temp.kadist.org/sites/kadist.org/files/mtdbt2f4d/eot/mtdbt2f4d.eot
		# http://temp.kadist.org/sites/kadist.org/files/mtdbt2f4d/woff/mtdbt2f4d.woff

		break
	else
		let CANDIDATE=CANDIDATE+1
		echo "No release candidate found. Trying again ..."		
	fi
	
	let COUNTER=COUNTER+1
	echo "candidate = $CANDIDATE"
	# sleep $SLEEP
done

# cleanup

rm -r "$LOCAL"/.pdf
rm -r "$LOCAL"/.png
rm -r "$LOCAL"/.ttf
rm -r "$LOCAL"/.eot
rm -r "$LOCAL"/.woff

# date and done

echo $(date)
echo "mtdbt2f4d-release exited ok."
echo "Thank you."
echo "*"
