#!/bin/bash

# init

EXTENSION=".mf"

# strip .mf and iterate over stdin

for FILE in "$@"
do
    STRIPPED=${FILE%$EXTENSION}
    mtdbt2f-compile --file $STRIPPED
done

echo -e "** mtdbt2f-compile-helper ok ** \r"
echo -e "Bye."

# end


